import { Controller, Get, Query, Res, UnauthorizedException } from '@nestjs/common';
import type { FastifyReply } from 'fastify';
import { jwtVerify } from 'jose';
import { ConfigService } from '@nestjs/config';
import { Public } from './public.decorator';

interface ImpersonationPayload {
  sub:             string;
  orgId:           string;
  impersonatedBy:  string;
  exp:             number;
}

/**
 * GET /api/v1/auth/impersonate?token=<signed-impersonation-token>
 *
 * Validates the short-lived HS256 impersonation token generated by
 * POST /admin/users/:id/impersonate and returns the decoded session.
 * In a full implementation this would set a session cookie and redirect
 * to /dashboard — for now it returns the decoded payload as JSON.
 */
@Controller('auth')
export class ImpersonateController {
  constructor(private readonly config: ConfigService) {}

  @Get('impersonate')
  @Public()
  async impersonate(
    @Query('token') token: string,
    @Res() reply: FastifyReply,
  ) {
    if (!token) throw new UnauthorizedException('No token provided.');

    const rawSecret = this.config.get<string>('IMPERSONATION_SECRET', 'dev-impersonation-secret');
    const secret    = new TextEncoder().encode(rawSecret);

    let payload: ImpersonationPayload;
    try {
      const { payload: p } = await jwtVerify<ImpersonationPayload>(token, secret);
      payload = p;
    } catch {
      throw new UnauthorizedException('Invalid or expired impersonation token.');
    }

    const appBase = this.config.get<string>('APP_BASE_URL', 'http://localhost:4000');

    // In a full implementation: set session cookie, redirect to dashboard.
    // Here we return the decoded context so the frontend can consume it.
    void reply.code(200).send({
      valid:           true,
      userId:          payload.sub,
      orgId:           payload.orgId,
      impersonatedBy:  payload.impersonatedBy,
      expiresAt:       new Date((payload.exp) * 1000).toISOString(),
      redirectTo:      `${appBase}/dashboard`,
      message:         'Impersonation token valid. Set this as your session and redirect to redirectTo.',
    });
  }
}
