import { PDFDocument, StandardFonts, rgb, type PDFPage, type PDFFont } from 'pdf-lib';
import type { RenderInput, RenderParty } from '../types';

const MARGIN = 50;
const LINE_H = 18;
const COL_WIDTHS = [180, 50, 80, 80, 60, 80]; // desc, qty, unit, price, disc%, total

export class PdfRenderer {
  /**
   * Generates a PDF/A-3 compatible invoice PDF.
   * Returns the PDF as a Uint8Array suitable for S3 upload.
   */
  async render(input: RenderInput): Promise<Uint8Array> {
    const doc = await PDFDocument.create();
    doc.setTitle(input.invoiceNumber);
    doc.setCreationDate(new Date());
    doc.setModificationDate(new Date());

    const font = await doc.embedFont(StandardFonts.Helvetica);
    const bold = await doc.embedFont(StandardFonts.HelveticaBold);
    const page = doc.addPage([595.28, 841.89]); // A4

    let y = 800;
    const w = page.getWidth() - MARGIN * 2;

    // ── Header ──────────────────────────────────────────────────────────────
    page.drawText('INVOICE', { x: MARGIN, y, font: bold, size: 22, color: rgb(0.1, 0.1, 0.7) });
    y -= LINE_H * 1.5;

    page.drawText(input.invoiceNumber, { x: MARGIN, y, font: bold, size: 13 });
    const dateStr = `Issued: ${fmtDate(input.issuedAt)}   Due: ${fmtDate(input.dueAt)}`;
    page.drawText(dateStr, { x: MARGIN + 200, y, font, size: 10 });
    y -= LINE_H * 2;

    // ── Parties ──────────────────────────────────────────────────────────────
    const halfW = (w - 20) / 2;
    y = drawPartyBlock(page, input.seller, 'FROM', MARGIN, y, halfW, bold, font);
    drawPartyBlock(page, input.buyer, 'TO', MARGIN + halfW + 20, y + LINE_H * 6, halfW, bold, font);
    y -= LINE_H;

    // ── Line table header ─────────────────────────────────────────────────────
    y -= LINE_H;
    const headers = ['Description', 'Qty', 'Unit', 'Unit Price', 'Disc.', 'Total'];
    let x = MARGIN;
    page.drawRectangle({ x: MARGIN, y: y - 2, width: w, height: LINE_H + 4, color: rgb(0.9, 0.9, 0.95) });
    for (let i = 0; i < headers.length; i++) {
      page.drawText(headers[i]!, { x: x + 2, y: y + 2, font: bold, size: 9 });
      x += COL_WIDTHS[i]!;
    }
    y -= LINE_H;

    // ── Lines ─────────────────────────────────────────────────────────────────
    for (const line of input.lines) {
      if (y < 150) { break; } // TODO: handle multi-page
      x = MARGIN;
      const cols = [
        line.description,
        String(line.quantity),
        line.unit,
        fmtMoney(line.unitPrice, input.currencyCode),
        line.discount ? `${(line.discount * 100).toFixed(0)}%` : '',
        fmtMoney(line.lineTotal, input.currencyCode),
      ];
      for (let i = 0; i < cols.length; i++) {
        page.drawText(cols[i]!, { x: x + 2, y, font, size: 9 });
        x += COL_WIDTHS[i]!;
      }
      y -= LINE_H;
    }

    // ── Separator ─────────────────────────────────────────────────────────────
    page.drawLine({ start: { x: MARGIN, y }, end: { x: MARGIN + w, y }, thickness: 0.5, color: rgb(0.7, 0.7, 0.7) });
    y -= LINE_H;

    // ── Totals ────────────────────────────────────────────────────────────────
    const totalsX = MARGIN + w - 200;
    const drawTotal = (label: string, amount: number, isBold = false) => {
      page.drawText(label, { x: totalsX, y, font: isBold ? bold : font, size: 10 });
      page.drawText(fmtMoney(amount, input.currencyCode), { x: totalsX + 130, y, font: isBold ? bold : font, size: 10 });
      y -= LINE_H;
    };
    drawTotal('Subtotal', input.subtotal);
    drawTotal(`VAT`, input.taxAmount);
    drawTotal('TOTAL DUE', input.total, true);

    // ── Note ──────────────────────────────────────────────────────────────────
    if (input.note) {
      y -= LINE_H;
      page.drawText(`Note: ${input.note}`, { x: MARGIN, y, font, size: 9, color: rgb(0.4, 0.4, 0.4) });
    }

    // ── Footer ────────────────────────────────────────────────────────────────
    page.drawText('Generated by Invoice Platform · EN 16931 compliant', {
      x: MARGIN,
      y: 30,
      font,
      size: 8,
      color: rgb(0.6, 0.6, 0.6),
    });

    return doc.save();
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function drawPartyBlock(
  page: PDFPage,
  party: RenderParty,
  label: string,
  x: number,
  y: number,
  _width: number,
  bold: PDFFont,
  font: PDFFont,
): number {
  page.drawText(label, { x, y, font: bold, size: 9, color: rgb(0.4, 0.4, 0.8) });
  y -= LINE_H;
  page.drawText(party.name, { x, y, font: bold, size: 11 });
  y -= LINE_H;
  if (party.vatNumber) { page.drawText(`VAT: ${party.vatNumber}`, { x, y, font, size: 9 }); y -= LINE_H; }
  if (party.street)    { page.drawText(party.street, { x, y, font, size: 9 }); y -= LINE_H; }
  if (party.city)      { page.drawText(`${party.postalCode ?? ''} ${party.city}`, { x, y, font, size: 9 }); y -= LINE_H; }
  if (party.country)   { page.drawText(party.country, { x, y, font, size: 9 }); y -= LINE_H; }
  if (party.iban)      { page.drawText(`IBAN: ${party.iban}`, { x, y, font, size: 9 }); y -= LINE_H; }
  return y;
}

function fmtDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

function fmtMoney(amount: number, currency: string): string {
  return new Intl.NumberFormat('en-EU', { style: 'currency', currency }).format(amount);
}
